import type { FastifyBaseLogger } from 'fastify';
import { ContentProcessingError, LLMError } from '../lib/errors.js';

/**
 * Email Response Formatter
 * Formats success and error email responses for users
 */

/**
 * Formatted email content ready to send
 */
export interface EmailContent {
  to: string;
  subject: string;
  body: string;
}

/**
 * Format success email response with LLM feedback
 *
 * Creates a well-formatted email response containing AI-generated feedback.
 * Subject follows "Re: <original>" pattern. Body includes greeting, feedback,
 * and footer with static signature.
 *
 * @param to - Recipient email address
 * @param originalSubject - Original email subject line (or empty for default)
 * @param feedback - LLM-generated feedback text (inserted verbatim)
 * @param logger - Optional Fastify logger for metadata tracking
 * @returns Formatted email content ready to send
 */
export function formatSuccessEmail(
  to: string,
  originalSubject: string,
  feedback: string,
  logger?: FastifyBaseLogger
): EmailContent {
  // Build subject line with "Re:" prefix
  const subject = originalSubject.trim()
    ? `Re: ${originalSubject}`
    : 'Re: Your email draft';

  // Build email body with template
  const body = `Hi,

I've analyzed your email draft and here's my feedback:

${feedback}

---
This analysis was generated by Email Analyzer
If you have questions, contact your CMO.`;

  // Validate body length and log warning if excessive
  if (body.length > 10000) {
    logger?.warn(
      {
        to,
        subject,
        bodyLength: body.length,
      },
      'Success email body exceeds 10,000 characters'
    );
  }

  // Log metadata (NOT actual feedback content)
  logger?.info(
    {
      to,
      subject,
      bodyLength: body.length,
    },
    'Success email formatted'
  );

  return {
    to,
    subject,
    body,
  };
}

/**
 * Format error email response for processing failures
 *
 * Creates user-friendly error email with appropriate template based on error type.
 * Content errors (NO_CONTENT, INVALID_FORMAT, etc.) suggest actionable fixes.
 * LLM errors (TIMEOUT, NETWORK_ERROR, etc.) suggest retry.
 *
 * @param to - Recipient email address
 * @param error - ContentProcessingError or LLMError with user message
 * @param logger - Optional Fastify logger for metadata tracking
 * @returns Formatted error email content ready to send
 */
export function formatErrorEmail(
  to: string,
  error: ContentProcessingError | LLMError,
  logger?: FastifyBaseLogger
): EmailContent {
  const subject = 'Email Analysis Error';

  // Select template based on error type
  let body: string;
  if (error instanceof ContentProcessingError) {
    // Content processing errors - user can fix the issue
    body = `Hi,

I couldn't analyze your email draft:

${error.userMessage}

Please correct the issue and try again.

---
Email Analyzer`;
  } else {
    // LLM errors - suggest retry
    body = `Hi,

I encountered an issue while analyzing your email:

${error.userMessage}

This is usually temporary. Please try sending your draft again in a moment.

---
Email Analyzer`;
  }

  // Log metadata (not technical details)
  logger?.info(
    {
      to,
      errorCode: error.code,
    },
    'Error email formatted'
  );

  return {
    to,
    subject,
    body,
  };
}
